In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('Machine Downtime.csv')
df.head()

Date            Machine_ID Assembly_Line_No  Hydraulic_Pressure(bar)  \
0  31-12-2021  Makino-L1-Unit1-2013     Shopfloor-L1                    71.04   
1  31-12-2021  Makino-L1-Unit1-2013     Shopfloor-L1                   125.33   
2  31-12-2021  Makino-L3-Unit1-2015     Shopfloor-L3                    71.12   
3  31-05-2022  Makino-L2-Unit1-2015     Shopfloor-L2                   139.34   
4  31-03-2022  Makino-L1-Unit1-2013     Shopfloor-L1                    60.51   

   Coolant_Pressure(bar)  Air_System_Pressure(bar)  Coolant_Temperature  \
0               6.933725                  6.284965                 25.6   
1               4.936892                  6.196733                 35.3   
2               6.839413                  6.655448                 13.1   
3               4.574382                  6.560394                 24.4   
4               6.893182                  6.141238                  4.1   

   Hydraulic_Oil_Temperature(?C)  Spindle_Bearing_Temperature(?C)  \
0                           46.0                             33.4   
1                           47.4                             34.6   
2                           40.7                             33.0   
3                           44.2                             40.6   
4                           47.3                             31.4   

   Spindle_Vibration(?m)  Tool_Vibration(?m)  Spindle_Speed(RPM)  \
0                  1.291              26.492             25892.0   
1                  1.382              25.274             19856.0   
2                  1.319              30.608             19851.0   
3                  0.618              30.791             18461.0   
4                  0.983              25.516             26526.0   

   Voltage(volts)  Torque(Nm)  Cutting(kN)         Downtime  
0           335.0   24.055326         3.58  Machine_Failure  
1           368.0   14.202890         2.68  Machine_Failure  
2           325.0   24.049267         3.55  Machine_Failure  
3           360.0   25.860029         3.55  Machine_Failure  
4           354.0   25.515874         3.55  Machine_Failure

In [3]:
df.columns

Index(['Date', 'Machine_ID', 'Assembly_Line_No', 'Hydraulic_Pressure(bar)',
       'Coolant_Pressure(bar)', 'Air_System_Pressure(bar)',
       'Coolant_Temperature', 'Hydraulic_Oil_Temperature(?C)',
       'Spindle_Bearing_Temperature(?C)', 'Spindle_Vibration(?m)',
       'Tool_Vibration(?m)', 'Spindle_Speed(RPM)', 'Voltage(volts)',
       'Torque(Nm)', 'Cutting(kN)', 'Downtime'],
      dtype='object')

In [4]:
#Removing unnecessary columns
df.drop(columns=['Date','Machine_ID','Assembly_Line_No'],axis=1,inplace=True)
df.head(2)

Hydraulic_Pressure(bar)  Coolant_Pressure(bar)  Air_System_Pressure(bar)  \
0                    71.04               6.933725                  6.284965   
1                   125.33               4.936892                  6.196733   

   Coolant_Temperature  Hydraulic_Oil_Temperature(?C)  \
0                 25.6                           46.0   
1                 35.3                           47.4   

   Spindle_Bearing_Temperature(?C)  Spindle_Vibration(?m)  Tool_Vibration(?m)  \
0                             33.4                  1.291              26.492   
1                             34.6                  1.382              25.274   

   Spindle_Speed(RPM)  Voltage(volts)  Torque(Nm)  Cutting(kN)  \
0             25892.0           335.0   24.055326         3.58   
1             19856.0           368.0   14.202890         2.68   

          Downtime  
0  Machine_Failure  
1  Machine_Failure

In [5]:
df.shape

(2500, 13)

In [6]:
df.columns

Index(['Hydraulic_Pressure(bar)', 'Coolant_Pressure(bar)',
       'Air_System_Pressure(bar)', 'Coolant_Temperature',
       'Hydraulic_Oil_Temperature(?C)', 'Spindle_Bearing_Temperature(?C)',
       'Spindle_Vibration(?m)', 'Tool_Vibration(?m)', 'Spindle_Speed(RPM)',
       'Voltage(volts)', 'Torque(Nm)', 'Cutting(kN)', 'Downtime'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 13 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Hydraulic_Pressure(bar)          2490 non-null   float64
 1   Coolant_Pressure(bar)            2481 non-null   float64
 2   Air_System_Pressure(bar)         2483 non-null   float64
 3   Coolant_Temperature              2488 non-null   float64
 4   Hydraulic_Oil_Temperature(?C)    2484 non-null   float64
 5   Spindle_Bearing_Temperature(?C)  2493 non-null   float64
 6   Spindle_Vibration(?m)            2489 non-null   float64
 7   Tool_Vibration(?m)               2489 non-null   float64
 8   Spindle_Speed(RPM)               2494 non-null   float64
 9   Voltage(volts)                   2494 non-null   float64
 10  Torque(Nm)                       2479 non-null   float64
 11  Cutting(kN)                      2493 non-null   float64
 12  Downtime            

In [8]:
df.describe()

Hydraulic_Pressure(bar)  Coolant_Pressure(bar)  \
count              2490.000000            2481.000000   
mean                101.409084               4.947058   
std                  30.289301               0.997357   
min                 -14.326454               0.325000   
25%                  76.355000               4.462464   
50%                  96.763486               4.939960   
75%                 126.415727               5.518401   
max                 191.000000              11.350000   

       Air_System_Pressure(bar)  Coolant_Temperature  \
count               2483.000000          2488.000000   
mean                   6.499275            18.559887   
std                    0.407279             8.554480   
min                    5.063480             4.100000   
25%                    6.217987            10.400000   
50%                    6.505191            21.200000   
75%                    6.780550            25.600000   
max                    7.973992            98.200000   

       Hydraulic_Oil_Temperature(?C)  Spindle_Bearing_Temperature(?C)  \
count                    2484.000000                      2493.000000   
mean                       47.618317                        35.063698   
std                         3.768674                         3.764823   
min                        35.200000                        22.600000   
25%                        45.100000                        32.500000   
50%                        47.700000                        35.100000   
75%                        50.100000                        37.600000   
max                        61.400000                        49.500000   

       Spindle_Vibration(?m)  Tool_Vibration(?m)  Spindle_Speed(RPM)  \
count            2489.000000         2489.000000         2494.000000   
mean                1.009334           25.411975        20274.792302   
std                 0.342898            6.437142         3852.660056   
min                -0.461000            2.161000            0.000000   
25%                 0.777000           21.089000        17919.000000   
50%                 1.008000           25.455000        20137.500000   
75%                 1.236000           29.790000        22501.750000   
max                 2.000000           45.726000        27957.000000   

       Voltage(volts)   Torque(Nm)  Cutting(kN)  
count     2494.000000  2479.000000  2493.000000  
mean       348.996792    25.234968     2.782551  
std         45.376024     6.138564     0.616688  
min        202.000000     0.000000     1.800000  
25%        319.000000    21.666115     2.250000  
50%        349.000000    24.647736     2.780000  
75%        380.000000    30.514008     3.270000  
max        479.000000    55.552400     3.930000

In [9]:
df.nunique() #no of unique values in each column

Hydraulic_Pressure(bar)            1977
Coolant_Pressure(bar)              1628
Air_System_Pressure(bar)           2472
Coolant_Temperature                 275
Hydraulic_Oil_Temperature(?C)       209
Spindle_Bearing_Temperature(?C)     204
Spindle_Vibration(?m)              1144
Tool_Vibration(?m)                 2350
Spindle_Speed(RPM)                 1180
Voltage(volts)                      238
Torque(Nm)                         1327
Cutting(kN)                         170
Downtime                              2
dtype: int64

In [10]:
df.isnull().sum() #total null values in each feature

Hydraulic_Pressure(bar)            10
Coolant_Pressure(bar)              19
Air_System_Pressure(bar)           17
Coolant_Temperature                12
Hydraulic_Oil_Temperature(?C)      16
Spindle_Bearing_Temperature(?C)     7
Spindle_Vibration(?m)              11
Tool_Vibration(?m)                 11
Spindle_Speed(RPM)                  6
Voltage(volts)                      6
Torque(Nm)                         21
Cutting(kN)                         7
Downtime                            0
dtype: int64

In [11]:
df.dropna(inplace=True) #removing rows with null values
df

Hydraulic_Pressure(bar)  Coolant_Pressure(bar)  \
0                   71.040000               6.933725   
1                  125.330000               4.936892   
2                   71.120000               6.839413   
3                  139.340000               4.574382   
4                   60.510000               6.893182   
...                       ...                    ...   
2494               131.894307               5.221555   
2495               112.715506               5.220885   
2496               103.086653               5.211886   
2498               145.855859               5.207777   
2499                96.690000               5.936610   

      Air_System_Pressure(bar)  Coolant_Temperature  \
0                     6.284965                 25.6   
1                     6.196733                 35.3   
2                     6.655448                 13.1   
3                     6.560394                 24.4   
4                     6.141238                  4.1   
...                        ...                  ...   
2494                  6.573392                 22.4   
2495                  6.196610                 22.3   
2496                  7.074653                 11.9   
2498                  6.402655                 12.2   
2499                  7.109355                 29.8   

      Hydraulic_Oil_Temperature(?C)  Spindle_Bearing_Temperature(?C)  \
0                              46.0                             33.4   
1                              47.4                             34.6   
2                              40.7                             33.0   
3                              44.2                             40.6   
4                              47.3                             31.4   
...                             ...                              ...   
2494                           45.5                             32.5   
2495                           48.8                             37.2   
2496                           48.3                             31.5   
2498                           44.5                             32.1   
2499                           53.2                             36.2   

      Spindle_Vibration(?m)  Tool_Vibration(?m)  Spindle_Speed(RPM)  \
0                     1.291              26.492             25892.0   
1                     1.382              25.274             19856.0   
2                     1.319              30.608             19851.0   
3                     0.618              30.791             18461.0   
4                     0.983              25.516             26526.0   
...                     ...                 ...                 ...   
2494                  1.276              23.430             20978.0   
2495                  0.910              20.282             20974.0   
2496                  1.106              34.708             20951.0   
2498                  0.995              26.498             20935.0   
2499                  0.840              31.580             23576.0   

      Voltage(volts)  Torque(Nm)  Cutting(kN)            Downtime  
0              335.0   24.055326         3.58     Machine_Failure  
1              368.0   14.202890         2.68     Machine_Failure  
2              325.0   24.049267         3.55     Machine_Failure  
3              360.0   25.860029         3.55     Machine_Failure  
4              354.0   25.515874         3.55     Machine_Failure  
...              ...         ...          ...                 ...  
2494           390.0   22.757270         2.94  No_Machine_Failure  
2495           282.0   22.761610         2.72  No_Machine_Failure  
2496           319.0   22.786597         2.94  No_Machine_Failure  
2498           376.0   22.804012         2.79  No_Machine_Failure  
2499           385.0   24.409551         3.55     Machine_Failure  

[2381 rows x 13 columns]

In [12]:
df.shape

(2381, 13)

In [13]:
df.notnull().sum() # 0 missing values

Hydraulic_Pressure(bar)            2381
Coolant_Pressure(bar)              2381
Air_System_Pressure(bar)           2381
Coolant_Temperature                2381
Hydraulic_Oil_Temperature(?C)      2381
Spindle_Bearing_Temperature(?C)    2381
Spindle_Vibration(?m)              2381
Tool_Vibration(?m)                 2381
Spindle_Speed(RPM)                 2381
Voltage(volts)                     2381
Torque(Nm)                         2381
Cutting(kN)                        2381
Downtime                           2381
dtype: int64

In [14]:
#Coverting categorical data into numerical data
df.loc[df['Downtime']=='Machine_Failure','Downtime']=1
df.loc[df['Downtime']=='No_Machine_Failure','Downtime']=0
df['Downtime'] = pd.to_numeric(df['Downtime'])
df.head(2)

Hydraulic_Pressure(bar)  Coolant_Pressure(bar)  Air_System_Pressure(bar)  \
0                    71.04               6.933725                  6.284965   
1                   125.33               4.936892                  6.196733   

   Coolant_Temperature  Hydraulic_Oil_Temperature(?C)  \
0                 25.6                           46.0   
1                 35.3                           47.4   

   Spindle_Bearing_Temperature(?C)  Spindle_Vibration(?m)  Tool_Vibration(?m)  \
0                             33.4                  1.291              26.492   
1                             34.6                  1.382              25.274   

   Spindle_Speed(RPM)  Voltage(volts)  Torque(Nm)  Cutting(kN)  Downtime  
0             25892.0           335.0   24.055326         3.58         1  
1             19856.0           368.0   14.202890         2.68         1

In [15]:
X=df.drop('Downtime',axis=1)
y=df['Downtime']

In [16]:
df['Downtime'].value_counts() #data is balanced

Downtime
1    1231
0    1150
Name: count, dtype: int64

In [17]:
#Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [18]:
X_train.shape

(1666, 12)

In [19]:
y_train

2478    0
956     1
2123    0
2326    1
769     1
       ..
1720    0
1158    1
1194    1
1365    1
909     1
Name: Downtime, Length: 1666, dtype: int64

In [20]:
#Feature Scaling
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
#Model training
from sklearn.linear_model import LogisticRegression
regressor=LogisticRegression()
model=regressor.fit(X_train,y_train)

In [22]:
model.coef_

array([[-7.7375885 ,  1.95239674,  0.03183064,  1.02501659, -0.37454646,
        -0.46575314,  0.06444451,  0.03028636,  2.01097746, -0.12202603,
        -5.68642741,  3.3129969 ]])

In [23]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,

In [24]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,classification_report

In [25]:
metrics=confusion_matrix(y_test,y_pred)
print(metrics)
print(classification_report(y_test,y_pred))

[[295  64]
 [ 46 310]]
              precision    recall  f1-score   support

           0       0.87      0.82      0.84       359
           1       0.83      0.87      0.85       356

    accuracy                           0.85       715
   macro avg       0.85      0.85      0.85       715
weighted avg       0.85      0.85      0.85       715



In [26]:
#Hyperparameter Tuning using GridSearchCV
from sklearn.model_selection import GridSearchCV

In [27]:
params=[{'C':[1,5,10,15,20,30,40,50]},{'max_iter':[100,150,200,300]}]

In [28]:
model1=GridSearchCV(model,param_grid=params,scoring='f1',cv=5)
model1.fit(X_train,y_train)


GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid=[{'C': [1, 5, 10, 15, 20, 30, 40, 50]},
                         {'max_iter': [100, 150, 200, 300]}],
             scoring='f1')

In [29]:
model1.best_params_

{'C': 5}

In [30]:
y_pred=model1.predict(X_test)

In [31]:
#Final accuracy
metrics=confusion_matrix(y_test,y_pred)
print(metrics)
print(classification_report(y_test,y_pred))

[[299  60]
 [ 45 311]]
              precision    recall  f1-score   support

           0       0.87      0.83      0.85       359
           1       0.84      0.87      0.86       356

    accuracy                           0.85       715
   macro avg       0.85      0.85      0.85       715
weighted avg       0.85      0.85      0.85       715



In [32]:
accuracy_score(y_test,y_pred)

0.8531468531468531

In [33]:
def classification_scores(org,pred):
    print("accuracy score: ",accuracy_score(org,pred))
    print("precision score: ",precision_score(org,pred))
    print("recall score: ",recall_score(org,pred))
    print("f1 score: ",f1_score(org,pred))

In [34]:
classification_scores(y_test,y_pred)

accuracy score:  0.8531468531468531
precision score:  0.8382749326145552
recall score:  0.8735955056179775
f1 score:  0.8555708390646493
